final Map<String, String> list1 = {
  'Feeling Afraid': 'FifthScreen',
  'Forgivness': 'NinthScreen',
  'For increase knowledge': 'EightScreen',
  'When seeing Muslim smiling': 'SeventhScreen',
  'Ascending or descending': 'TwelfthScreen',
  'Thanking someone': 'SixthScreen',
  'Sneezing': 'FourthScreen',
  'Visiting ill': 'EleventhScreen',
  'When it rains': 'TenthScreen',
  'For rain': 'RainsScreen',
//
  'Before meal': 'BeforeMealScreen',
  'Forget dua before meal': 'ForgetduaScreen',
  'After meal': 'AfterMealScreen',
  'Drinking milk': 'MilkduaScreen',
  'When dining someones house': 'DiningScreen',
  'Before going to bed': 'BedduaScreen',
  'When waking up': 'WakingupScreen',
  'When entring the toilet': 'EntringScreen',
  'When leaving the toilet': 'LeavingScreen',
  'When hear bad news': 'BadnewsScreen',
//
  'Wearing clothes': 'WearingclothsScreen',
  'Before undressing': 'UndressingDuaScreen',
  'Wearing new clothes': 'WearingnewClothesScreen',
  'When seeing mirror': 'SeeingmirrorScreen',
  'When Entring the house': 'EntringhouseScreen',
  'When leaving the house': 'LeavinghouseScreen',
  'When entring the Masjid': 'EntringMasjidScreen',
  'When leaving the Masjid': 'LeavingMasjidScreen',
  'When doing Wudu': 'DoingWuduScreen',
  'After Wudu': 'AfterWuduScreen',
//
  'After adhan': 'AfteradhanScreen',
  'After Salah': 'AfterSalahScreen',
  'Boarding a vehicle': 'BoardingvehicleScreen',
  'Seeing new moon': 'SeeingnewmoonScreen',
  'Hear the voice of donkey': 'DuringdonkeyvoiceduaScreen',
  'At the time of Iftar': 'IftartimeScreen',
  'For Lailatulqadar': 'LailatulqadarScreen',
  'Seeking good in this world and Akhirah': 'WorldandAkhirahScreen',
  'Visting graveyard': 'VisitingGraveyardScreen',
  'During rainstorm': 'ExcessiveRainScreen',
};
